# Heartbeat - Uptime monitoring

heartbeat.monitors:
  # HTTP monitoring
  - type: http
    id: elasticsearch-monitor
    name: Elasticsearch
    schedule: '@every 30s'
    urls:
      - http://elasticsearch:9200
    check.response.status: [200]

  - type: http
    id: kibana-monitor
    name: Kibana
    schedule: '@every 30s'
    urls:
      - http://kibana:5601
    check.response.status: [200]

  # TCP monitoring
  - type: tcp
    id: logstash-tcp
    name: Logstash TCP
    schedule: '@every 30s'
    hosts:
      - logstash:5044

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "heartbeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: false

logging.level: info
logging.to_files: false
